### PR TITLE
add some Logo

### PR DESCRIPTION
**Pull request by panpan0000**

### CODE REVIEW

**Review by ronaldpetty — CHANGES_REQUESTED** [review]
@panpan0000 thanks for contribution. Can you remove the png logos? Unfortunately, PNG is not supported, only SVG.

**Comment by panpan0000** [comment]
> @panpan0000 thanks for contribution. Can you remove the png logos? Unfortunately, PNG is not supported, only SVG.

thanks for reminder!
I found those logo from their website and github. I will try to dig svg format instead and update PR

**Comment by panpan0000** [comment]
all fixed , @ronaldpetty , thanks for your time to review again, please.

**Comment by zanetworker** [comment]
@panpan0000 this is a useful resource: https://github.com/cncf/artwork/tree/main/projects (where all CNCF artwork is located), they have it in PNG and SVG as inspiration. We could also use logos from LFAI: https://github.com/lfai/lfai-landscape/tree/main/hosted_logos

**Review by ronaldpetty — APPROVED** [review]
lgtm thanks for update

**Pull request merged**
